name: CI

on: push

jobs:
  my-job:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Basic Checks
      env:
        ZSHRC_PATH: zsh/.zshrc
      run: |
        sudo apt install shellcheck
        shellcheck ${ZSHRC_PATH}
        ls -l